title: Craftplacer's Site
url: "https://craftplacer.github.io"
permalink: /posts/:title
lang: en
twitter: "@Craftplacer"

plugins:
  - jekyll-feed

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
