title: "Craftplacer's Site"
shortTitle: "crtplr"
description: "This is Craftplacer's personal page, containing blog posts and various other things."

author: "Craftplacer"
url: "https://craftplacer.github.io"
permalink: "/posts/:title"
encoding: utf-8
theme: null

plugins:
  - jekyll-feed

collections:
  cookbook:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
