source "https://rubygems.org"

gem "jekyll", "~> 4.2.1"
# gem "github-pages", group: :jekyll_plugins

group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12"
  gem "jekyll-titles-from-headings"
  gem "jekyll-include_sass"
  gem "jekyll-redirect-from"
  gem "jekyll-postfiles"
  # search engine cancer
  gem "jekyll-sitemap"
  gem "jekyll-seo-tag"
  gem "jekyll-google_search_console_verification_file"
end

platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", "~> 1.2"
  gem "tzinfo-data"
end

gem "wdm", "~> 0.1.1", :platforms => [:mingw, :x64_mingw, :mswin]
gem "webrick", "~> 1.7"