name: Jekyll

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 0 * * 1'

env:
  JEKYLL_ENV: production

jobs:
  jekyll:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0
        bundler-cache: true

    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      uses: limjh16/jekyll-action-ts@v2
      with:
        jekyll_src: './src/'
        format_output: true
        custom_opts: '-d ./publish/'

    - name: Download Kaiteki subsite
      run: wget -O kaiteki.zip https://nightly.link/Kaiteki-Fedi/Website/workflows/build/master/website.zip
      
    - name: 'Create directories'
      run: 'mkdir -p ./publish/projects/kaiteki/'
      
    - name: Extract Kaiteki subsite
      run: 'unzip -d ./publish/projects/kaiteki/ kaiteki.zip'

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./publish/
        cname: craftplacer.moe
