name: Jekyll

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  jekyll:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0

    - name: Checkout
      uses: actions/checkout@v2
      
    - name: 'Checkout (Kaiteki)'
      uses: actions/checkout@v2
      with:
        repository: 'Kaiteki-Fedi/Website'
        path: './kaiteki'

    - name: Build
      uses: limjh16/jekyll-action-ts@v2
      with:
        jekyll_src: './src/'
        format_output: true
        custom_opts: '-d ./publish/'

    - name: 'Create directories'
      run: 'mkdir -p ./publish/projects/kaiteki/'

    - name: 'Build (Kaiteki)'
      uses: limjh16/jekyll-action-ts@v2
      with:
        jekyll_src: './kaiteki/src/'
        format_output: true
        custom_opts: '-d ./publish/projects/kaiteki/'

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./publish/
        cname: craftplacer.moe