name: Jekyll

on:
  push

jobs:
  jekyll:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    - name: "Checkout (Kaiteki)"
      uses: actions/checkout@v2
      with:
        repository: 'Kaiteki-Fedi/Website'
        path: "./kaiteki"

    - name: "Build (Kaiteki)"
      uses: helaili/jekyll-action@v2
      with:
        jekyll_src: './kaiteki/src/'
        jekyll_build_options: "-d ./src/projects/kaiteki"
        build_only: true
        
    - name: "Checkout"
      uses: actions/checkout@v2

    - name: "Build & Deploy"
      uses: helaili/jekyll-action@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        jekyll_src: './src/'
        target_branch: 'gh-pages'